### ISSUE TITLE
Add DROA storages to WHAM DMI

### ISSUE THREAD

**Issue by apivarnik** [usbr/crmms#125]
Add DROA storages to WHAM DMI so the historical accounting data loads correctly. It is only in the HDBtoRiverWare DMI

**Comment by stighi** [comment]
What is this new WHAM DMI and why is it there? Why is the HDBtoRiverWare DMI not being used to initialize anymore? There are some problems with that DMI and the lower basin has not been solving correctly in UC since it started being used. It is solving correctly in LC since we are not using that WHAM DMI, but rather the HDBtoRiverWare DMI.

**Comment by stighi** [comment]
After discussion, it was decided that we would make some changes to the WAM script and discontinue the use of this Input DMI. Now the HDBto RiverWare Input DMI is the only Input DMI used in 24MS mode for initialization and set up.
