### ISSUE TITLE
Negative Havasu Outflow seen in dev testing tool runs

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/crmms#27]
A few dev testing tool runs initialize Powell and Mead at very low pool elevations and also have low hydrology input flows. During a few of these runs, Lake Havasu calculates a negative outflow since users above Havasu take more water than is available. Havasu's outflow is solved based on the input target storage with no checks for the mass balance. This is done in the function GetTargedStorage(). 

I compared the CRMMS logic to the CRSS logic and they differ slightly. CRSS checks to see if the outflow from the RuleCurveStorage() would result in a negative storage. If the outflow would not be negative, it sets the storage to the target. I propose trying to emulate what CRSS is doing, which would add extra checks on the outflow and hopefully solve this issue. I have not tried to implement this yet. CRMMS has a function with the same name as the CRSS function, but it does not perform the same checks as the CRSS function.

There was discussion how to handle use in the LB. At this time, CRSS assumes hydrologic priority. I'd assume we'd do the same for now. 

Note: this same logic is used at Mohave and would likely need to be updated there.

## CRMMS Logic:
![CRMMS_Havasu](https://user-images.githubusercontent.com/18153871/114750250-04795f00-9d11-11eb-94de-2ec6ee7017b0.PNG)

## CRSS Logic:
![CRSS_Havasu](https://user-images.githubusercontent.com/18153871/114750248-04795f00-9d11-11eb-8124-519b42a9ccca.PNG)

**Comment by rabutler-usbr** [comment]
Previously https://github.com/usbr/MTOM/issues/159

**Comment by sbaker2423** [comment]
I tested the login with both the Havasu and Mohave development. I ran the development testing tool and the results looked as expected. There are no more negative outflows solved for from Lake Havasu.

**_The logic is summarized below._**
The previous ruleset set the storage of Havasu to the rule curve and solved for the outflow without considering constraints like active capacity and max/min releases. During a very wet year when the model was initialized with high Powell and Mead pool elevations, the development ruleset first solves for the outflow given the rule curve elevations, then constraints it to the max release. But in some scenarios, the max release is too low putting the storage above the active capacity. In this highly unlikely situation, the model releases above the max release in order to keep the storage at the max capacity. During dry hydrologies and initial conditions, the development ruleset releases the min release unless the water isn't available, then the reservoir releases whatever is possible.
