### ISSUE TITLE
Flaming Gorge WHAM upper limit drawdown pool elevation correction 

### ISSUE THREAD

**Issue by ntodea** [usbr/crmms#33]
Running the WHAM for the max 24MS the wrong upper limit drawdown pool elevation was calculated for end of April 2023.  The FG April-July 2023 forecast is 1302kaf, ~33% exceedance value. Per the FEIS, the upper limit drawdown pool elevation is 6025' (30.1-40 unregulated inflow forecast percentage exceedance range). The WHAM pool elevation value at the end of April 2023 came back as 6027.06'. The May 1, upper limit drawdown pool elevation needs to be adjusted to reflect the FEIS table 2-3.

**Comment by cfelletter** [comment]
Need this done by September 24MS since this will be effecting CRMMS results too

**Comment by cfelletter** [comment]
9/2/2021 Chat with Heather and Nate:
They need to be changed in both models. The description of what the ruleset should do and the code is different. It's missing a comparison between last year's volume and the current year. It is also not separating the months correctly. January and February should have the baseflow set using the previous year's unreg inflow. March should look at the previous year's inflow, but the priority is the current year inflow to meet the May 1 ULDE. The code has changed from the description.  ![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/36745146/131928100-807ca20f-d33c-4e2f-ae26-e014c5c48db3.png)
I also wrote the code for monthly operations. Here's the base flow calculation code (in pieces): 

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/36745146/131928108-51df9d91-e2ae-4e27-a254-3cded1abc427.png)
There is a typo in the last section and it should be "current year" rather than "next year". Otherwise, this should take care of all the issues with ULDE on May 1

One other thing with the spring volume calculations. You need to add back in the depletions like this: 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/36745146/131928104-63260cb2-bfff-455b-945e-2fbbd65724b7.png)

**Comment by cfelletter** [comment]
Jim "if we can we should represent what the operators do: we have perfect knowledge than we preterb this to represent the error of the forecast" - should we do this for FG? Explain to Jim what is going on.

**Comment by cfelletter** [comment]
@hpatno I'm reviewing these changes to CRMMS and I have a few questions. Perhaps we can schedule at time with you and @ntodea to discuss. Here is what I understand:

 GetFGBaseFlowMagnitudeUnconstrained()
1. Just to clarify: we are changing Jan-Mar to look at the inflow for the whole August-April period BUT in May-Dec we are still looking at it @t - @April Next Year? Why not August Current to April Next?
2. The code handles Jan-Feb differently than March. In Jan-Feb it will check Max Target HW(), MinFlow AND FG baseflow to meet the lower baseflow limit set for the Green at Jensen = FG baseflow + predicted Yampa flow. In March I don't check Jensen and have note: "CF: The EIS has no Jensen targets in March and April, in these months release are used to meet the UDLE. " Is this correct? Your screenshot code lumps them. 
3. I think April Next Year is correct for May-Dec logic, why would it be Current Year (in the past)? I get that you want to base the baseflow releases on the current years flows but the target is still May 1 Next Year. Can we discuss this further?

SpringFlowA-JVolumeUpdate() 
4. **CRSS only: FGTransbasinDepletions()**  only calls CO Schedules.FlamingGorgePipeline_COExportPotential_Depletion Requested which is not part of the model anymore. Sound correct?
5. RE: SpringFlowA-JVolumeUpdate()'s missing **comparison between last year's volume and the current year**: Currently in Jan-Mar, the April-July volume forecast is calculated as the average volume for that period multiplied by the ratio of the current year's forecast volume from the current month through April to the average for the same period. – Should we stop using this average "ForecastData.FGAverageUnregInflow" slot in favor of last years observed volume?

**Comment by hpatno** [comment]
Hi @cfelletter,

We do need to schedule time soon to get this cleared up. You previously sent me the spring volume rule as the issue with the March and April volume releases and computation for May 1 elevation. What has changed?

GetFGBaseFlowMagnitudeUnconstrained()

Just to clarify: we are changing Jan-Mar to look at the inflow for the whole August-April period BUT in May-Dec we are still looking at it @t - @april Next Year? Why not August Current to April Next? _The code separates March and April for the baseflow period. Using August current doesn't account for observed inflows and would lead to inaccurate calculations. _

The code handles Jan-Feb differently than March. In Jan-Feb it will check Max Target HW(), MinFlow AND FG baseflow to meet the lower baseflow limit set for the Green at Jensen = FG baseflow + predicted Yampa flow. In March I don't check Jensen and have note: "CF: The EIS has no Jensen targets in March and April, in these months release are used to meet the UDLE. " Is this correct? Your screenshot code lumps them.  _I don't see my screenshot lumping them for baseflow volume release calculations. If you don't recall, we had these discussions regarding FG operations in March and April being transition months and not including ROD baseflow restrictions. ROD operations are different for every reservoir. I believe your note came from past discussions regarding incorrect code manipulation.  You did a great job commenting the code I wrote. Thank you for all your work on that effort._

I think April Next Year is correct for May-Dec logic, why would it be Current Year (in the past)? I get that you want to base the baseflow releases on the current years flows but the target is still May 1 Next Year. Can we discuss this further? _The code is correct._

SpringFlowA-JVolumeUpdate()
4. CRSS only: FGTransbasinDepletions() only calls CO Schedules.FlamingGorgePipeline_COExportPotential_Depletion Requested which is not part of the model anymore. Sound correct? _I'm really concerned about this because all the depletions above FG including Colorado and Wyoming should be accounted for in the rules, and not just one. This is computing inaccurate unreg inflow volumes to compare against for hydrologic classification determinations._

5. RE: SpringFlowA-JVolumeUpdate()'s missing comparison between last year's volume and the current year: Currently in Jan-Mar, the April-July volume forecast is calculated as the average volume for that period multiplied by the ratio of the current year's forecast volume from the current month through April to the average for the same period. – Should we stop using this average "ForecastData.FGAverageUnregInflow" slot in favor of last years observed volume? _We should continue using that slot because the forecast trends to average for future conditions and it more accurately represents volumes used in operations._

**Comment by cfelletter** [comment]
Hi everyone, could I make a minor change to CRMMS after doing the sensitivity analysis? 

Overview: during the WHAM CRMMS run for the August Most Probable 24MS, Nate raised an issue with how the rules calculated the outflow required to meet the May 1 ULDE target elevation. During January - March, the April-July volume forecast volume is calculated as the average volume for that period multiplied by the ratio of the current year's forecast volume from the current month through April to the average for the same period. This was done to incorporate some uncertainty and ensure operations were sufficiently conservative should the forecast change.

Nate’s issue was due to this conservative estimation of releases in March, FG could not release enough in April to make the May 1 target.  

After reviewing with Heather we have decided to remove March from this period of simulated uncertainty. 
 
![image](https://user-images.githubusercontent.com/36745146/134578556-1efa7483-a799-4db2-a905-d841ce23cb62.png)

In the future we might revisit how both model simulate uncertainty in the FG forecast, if CRSS should be brought more into line with what is done in CRSS at Lake Powell. Also if CRMMS should simulate this uncertainty at all.

**Comment by cfelletter** [comment]
HP: can you quickly try this code? In the wet hydrology classification have the spring volume calculation use the forecast, but for all other classifications use the conservative estimate. The observed hydrological forecast uncertainty using empircal data from 2011 and 2017 indicate that the RFC models based on snowpack are more accurate during wet hydrologic classification years. Greater uncertainty exists in the dry-moderately wet years. Just add an if statement and it should fix the issues while maintaining some uncertainty related to forecasting. 

CF: It's not quite that simple since this volume is used before you have the HClass for the current month. We can use the HClass for last month, that only is computed for the BaseflowHClass (which is okay I think) 
![image](https://user-images.githubusercontent.com/36745146/134744057-4a962989-c965-470d-a0b4-e3534fd2ea8b.png)
And we haven't talk about the baseflow volume which I think is important to be modifying too and I hadn't modified in my previous run since we didn't discuss. 
![image](https://user-images.githubusercontent.com/36745146/134744117-fff9bb99-35a0-4198-9749-634034a48450.png)
And of course some provision will have to be made from runs starting in March which don't have the BaseFlowHClass[@t-1]

**Comment by cfelletter** [comment]
- [ ] Solution for runs starting in March which don't have the BaseFlowHClass[@T-1]

**Comment by cfelletter** [comment]
![image](https://user-images.githubusercontent.com/36745146/155821362-885aaf09-f895-4d88-9040-e74cb342173b.png)


Arguements: None

Description:
RPL logic my two new functions AprJulPercentExceedanceBaseFlow() and AprJulPercentExceedanceSpringFlow() matches that in rule 'Calc Percent Exceedance' except that the rule calls slots "KNN_MTOM.AprJulVolSpringFlow" and "KNN_MTOM.AprJulVolBaseFlow" which involve forecast adjust to account for the greater uncertainty exists in the dry-moderately wet years.  

Returns: Exceedance 0-1
