### ISSUE TITLE
Blue Mesa minimum elevation limit 

### ISSUE THREAD

**Issue by stighi** [usbr/crmms#39]
The CRMMS model logic maintains a minimum elevation at Blue Mesa of about 7,424 feet. 

Per Rick and Erik (email 9/15/21), the logic should be changed as follows:
If the CRMM rules are restricting Aspinall releases to prevent Blue Mesa from falling below 7424 feet this is not accurate modeling of the Aspinall Operation.  Erik and I believe that we would ensure minimum flows in the Black Canyon (300 cfs) are maintained and also WW minimum base flows are maintained.  We would allow Blue Mesa elevation to fall below 7424 feet and potentially below 7393 feet which is top of active storage before we would consider lowering river flows to conserve storage.  At 7393 feet we would lose the Blue Mesa powerplant but could still bypass water to meet flow targets and maintain Morrow Point and Crystal storage.

**Comment by cfelletter** [comment]
There is no logic protecting 7424 specifically. . What is causing it is a limit that outflow be <=  ReleaseableVolumeRate(). This is a function written by PWRE which "determines the maximum releaseable volume rate which is the max outlet works volume plus the volume above the spillway.  These statements where added to MTOM in 2017 to check that the release to meet ROD objectives is doable so that the spillway at BM is available.  This is a work around that Mike came up with.  Ideally we would prefer to somehow model daily operations during the peeking period to insure that the max release rate at BM is sufficient to support storage in MP.  Without the spillway, if releases from CR exceed around 6500 cfs, MP releases will exceed max BM releases and MP storage will fall.  Any releases required releases above about 6030 cfs at BM must come through spillway."  

Disabling this function allow PE to fall. I want to get @rclaytonrclayton to confirm this is desirable. 

There is logic which protects going below 7393 in BlueMesaOutflowCalc( MaximumRelToAvoidMinimumPE() )
