### ISSUE TITLE
GainsCrystalToGJ MIN Probable too High Nov/22

### ISSUE THREAD

**Issue by cfelletter** [usbr/crmms#42]
The October CBRFC Min Probable has GainsCrystalToGJ as the highest flow in all the traces for Nov/22

- [ ] Check Nov CBRFC ensemble. Is there an issue?

**Comment by cfelletter** [comment]
![image](https://user-images.githubusercontent.com/36745146/142241051-c7003440-b1b2-4c26-a6bf-e0797c41e37c.png)
Looks like it still exists in the Nov forecast.

**Comment by cfelletter** [comment]
RC explained this forecast only effects the first CRMMS rules run in the 24MS process. I've suggested that RC/EK follow up with the CBRFC but am not pursuing it further. 

@rclaytonrclayton "It looks like a blown forecast from the CBRFC.  If this were a reservoir forecast we would stop the presses and get it fixed.  But since this is our automated CRMMS run Erik and I wouldn't be impacted by it.  This forecast is only used in the rules for the CRMMS run.  Erik and I don't use this forecast when we develop operations for 24MS.  We pick our own forecast for this point.  

Yes but for all 3 runs MIN, MOST, MAX.  I look at the BM unreg inflow forecast and I find an  analogue year to match and use the analogue year hydrology as input for Uncompahgre, North Fork of Gunnison and unmeasured gains to Gunnison above Grand Junction.  We have never used this forecast in the 24MS process.

For the MIN if find an analogue year, for the MOST if find another analogue year and for the MAX I find yet another analogue year."

**Comment by stighi** [comment]
How is this forecast point being used in the MRM runs? If it is not an appropriate or useful forecast point, is there something else that should be used instead? Or something else that should be done in the logic? This forecast point was added back when someone else was operating Aspinall, so if there is something else that Rick has found that is superior to this forecast point, what could/should be done in the ESP runs?

**Comment by cfelletter** [comment]
@stighi it is being considered when calculating the flow requirement at Whitewater. A high inflow might meet the flow requirement itself, requiring little more than Tunnel + Black Canyon Minimum flows to pass from Crystal. The inflow point is needed to match current operations which consider side inflows. The analog year process @rclaytonrclayton mentioned is not something we model in any of the UB reservoirs. IMHO we don't need a change we just need to consult the CBRFC about this bad forecast.

**Comment by rclaytonrclayton** [comment]
I see my name mentioned so I will speak to this.

CRMMS is a monthly model.  Aspinall is operated on a daily timestep.  A monthly forecast for the gains above GJ is basically meaningless.  It exists to help the rules in CRMMS for Aspinall to solve but it has very little to do with actual operational decisions.  It is a work around to deal with the fact that Aspinall in CRMMS must be solved on a monthly time step.  We really need a daily model in rule based operation to solve multi trace runs. That is what is needed.

Rick

________________________________
From: Shana Tighi ***@***.***>
Sent: Wednesday, November 17, 2021 10:42 AM
To: usbr/crmms ***@***.***>
Cc: Clayton, Richard B ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [usbr/crmms] GainsCrystalToGJ MIN Probable too High Nov/22 (Issue #42)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



How is this forecast point being used in the MRM runs? If it is not an appropriate or useful forecast point, is there something else that should be used instead? Or something else that should be done in the logic? This forecast point was added back when someone else was operating Aspinall, so if there is something else that Rick has found that is superior to this forecast point, what could/should be done in the ESP runs?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fusbr%2Fcrmms%2Fissues%2F42%23issuecomment-971809284&data=04%7C01%7Crclayton%40usbr.gov%7C27ff98be185d415e5c5008d9a9f1a505%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637727677594125706%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jyRtsjY1DLCF%2BQ%2FXuxx%2FTOX2p51f%2F8OhqMhWHdCpSIA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHGA22TSDT6R7QR3S5HKMB3UMPSO7ANCNFSM5HJSEW5Q&data=04%7C01%7Crclayton%40usbr.gov%7C27ff98be185d415e5c5008d9a9f1a505%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637727677594135659%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uR%2Bfnr8p4IwL291NO%2FKbztNojD3VkBy3scubpQa4zLA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crclayton%40usbr.gov%7C27ff98be185d415e5c5008d9a9f1a505%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637727677594135659%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3F%2BdOHeMKte%2Fh7POO0yaBCgbZhaCQnVDXl8OCH8zG0o%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crclayton%40usbr.gov%7C27ff98be185d415e5c5008d9a9f1a505%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637727677594145608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TAe8%2FFe2ZXtlPf6CzFXiEl6Geb%2FU6kS2CfYr0BZgs4I%3D&reserved=0>.

**Comment by cfelletter** [comment]
@rclaytonrclayton I understand you're point but it's beyond the scope of this issue.  If one day UC Water Ops is able to rekindle Beau's daily model development for the Gunnison I'll be there to review. In the meantime, calling CRMMS operations meaningless doesn't help anything. Increased scrutiny on UB results and Drought Responce Operations accounting is on the horizon for CRMMS.  Erik has agree to follow up with CBRFC and we will see what they say. 

If there are problems with the historical HDB record maybe this is getting to the CBRFC. The analog years you guys are using for 1991-2020 should have similar monthly volumes to the ESP ensemble. It wouldn't hurt to keep and eye on the ESP gains at this site.

**Comment by cfelletter** [comment]
RC on 12/1/2021 email: "What we get from CBRFC (depending on the month of the year) is a MOST probably monthly forecast that extend to the end of the current WY.  This forecast is made up of the 3 month forecast product for the first 3 month and the remaining months of the water year are based on the ESP median results.  For the MIN probable and the MAX probable the CBRFC only provides us with a WY total forecast and it is not broken down by month.

Nate and Mark are responsible for taking the forecast information from the CBRFC and massaging it to fit the needs of CRMMS/24MS.  For the MIN and MAX probable this requires disaggregating the WY total forecast value to a monthly distribution.  This is NOT done in HDB.  It is done in a spreadsheet tool that Nate and Mark update each month. There a number of assumptions for how to do this disaggregation is done and there is not a consensus among our operations team for these assumptions.  There are number of ways to dissagregate the MIN and MAX probable WY total forecast values. The current methodology used can result in the MIN monthly distribution having values that exceed the MOST probable monthly forecast provided by the CBRFC.  If we continue to hang our hat on this current methodology we must accept that sometimes the MIN will be greater than the MOST.  We could change our methodology to prevent this from happening but it will be a change in our business practice that should be discussed among the group to make sure we are all onboard with a change.  I do know that Nate is concerned about this but he can't make a unilateral change without fully vetting the change within the group."
